### ISSUE TITLE
Publish image to dockerhub?

### ISSUE THREAD

**Issue by mwarkentin** [augmentable-dev/gitqlite#11]
It'd be nice if we could just run `docker run -v `pwd`:/repo:ro gitqlite "SELECT * FROM commits"` without needing to clone and build the docker image locally.

**Comment by michiel** [comment]
You can configure Automated Builds on hub.docker.com. This has the added benefit of having the build be public.

> Docker Hub can automatically build images from source code in an external repository and automatically push the built image to your Docker repositories.

[https://docs.docker.com/docker-hub/builds/](https://docs.docker.com/docker-hub/builds/)

If the name of the organisation on hub.docker.com is `augmentable-dev`, the command would look like,

```
docker run -v `pwd`:/repo:ro augmentable-dev/gitqlite:latest "SELECT * FROM commits"
```

**Comment by patrickdevivo** [comment]
Thanks @michiel, just wanted to follow up here that I've setup this repo on the docker hub registry: https://hub.docker.com/repository/docker/augmentable/gitqlite

I will close this issue out when I open a PR to add that to the docs

**Comment by mwarkentin** [comment]
@patrickdevivo nice, thanks!
