### ISSUE TITLE
请教一下，SQL语法的解析如何实现的？

### ISSUE THREAD

**Issue by lycclsltt** [augmentable-dev/gitqlite#17]
请教一下，SQL语法的解析如何实现的？又是如何和git查询接口对接上的呢

**Comment by sharefantasy** [comment]
看源码是, 工具启动的时候在内存里创建了sqlite数据库, 把git元信息提取出来加载到数据库里, 再把用户的查询放到那个sqlite库里查. 就是go-git和go-sqlite3互相倒腾.

**Comment by lycclsltt** [comment]
Thanks!
