### ISSUE TITLE
Following installation instructions doesn't work?

### ISSUE THREAD

**Issue by erezsh** [augmentable-dev/gitqlite#3]
I'm not very familiar with Go, so perhaps I'm doing something wrong?

```bash
$ go install -v -tags=sqlite_vtable github.com/augmentable-dev/gitqlite
can't load package: package github.com/augmentable-dev/gitqlite: cannot find package "github.com/augmentable-dev/gitqlite" in any of:
        /usr/lib/go-1.10/src/github.com/augmentable-dev/gitqlite (from $GOROOT)
        /home/erez/go/src/github.com/augmentable-dev/gitqlite (from $GOPATH)
```

**Comment by youngminz** [comment]
I was able to build successfully with the command below:

```bash
git clone https://github.com/augmentable-dev/gitqlite.git
cd gitqlite
make build
sudo cp gitqlite /usr/local/bin
gitqlite -h
```

**Comment by erezsh** [comment]
That gives me a different error. Sorry if I'm missing something obvious

```sh
$ go build
gitqlite.go:4:2: cannot find package "github.com/augmentable-dev/gitqlite/cmd" in any of:
        /usr/lib/go-1.10/src/github.com/augmentable-dev/gitqlite/cmd (from $GOROOT)
        /home/erez/go/src/github.com/augmentable-dev/gitqlite/cmd (from $GOPATH)
```

**Comment by youngminz** [comment]
Hmm... Does the same error occur when running `make` and `make build`?

I think there may be a problem with the version of golang. I am using Ubuntu 20.04 on wsl2, and the version of go is:
```
$ go version
go version go1.13.8 linux/amd64
```

**Comment by erezsh** [comment]
Mine was
```shell
go version go1.10.4 linux/amd64
```

It's what `apt install golang` gave me.

Upgrading manually to 1.14 solved it, but now it's missing sqlite bindings:

```shell
$ go build
# github.com/augmentable-dev/gitqlite/pkg/gitqlite
pkg/gitqlite/git_log.go:21:70: undefined: sqlite3.VTab
pkg/gitqlite/git_log.go:49:71: undefined: sqlite3.VTab
pkg/gitqlite/git_log.go:55:31: undefined: sqlite3.VTabCursor
pkg/gitqlite/git_log.go:82:39: undefined: sqlite3.InfoConstraint
pkg/gitqlite/git_log.go:82:68: undefined: sqlite3.InfoOrderBy
pkg/gitqlite/git_log.go:82:91: undefined: sqlite3.IndexResult
pkg/gitqlite/git_ref.go:20:70: undefined: sqlite3.VTab
pkg/gitqlite/git_ref.go:34:71: undefined: sqlite3.VTab
pkg/gitqlite/git_ref.go:58:39: undefined: sqlite3.InfoConstraint
pkg/gitqlite/git_ref.go:58:68: undefined: sqlite3.InfoOrderBy
pkg/gitqlite/git_ref.go:58:68: too many errors
```

**Comment by youngminz** [comment]
If you can use Docker, you can use how to build binaries within Docker. It builds in a clean environment, so it will probably succeed. :)

Dockerfile:
```
FROM golang:1.14

RUN cd / && \
   git clone https://github.com/augmentable-dev/gitqlite.git && \
   cd /gitqlite && \
   make build
```

Run:
```bash
docker build -t gitqlite-build .
docker run --rm gitqlite-build cat /gitqlite/gitqlite > gitqlite
chmod a+x gitqlite
sudo cp gitqlite /usr/local/bin
```

I hope you will go well!

**Comment by erezsh** [comment]
I mean, it shouldn't be that hard to install.

I was thinking of using this as an added feature in my project. But if my users will need a docker just to use it, it's probably not worth it.

But thanks for taking the time, and cool idea.

**Comment by youngminz** [comment]
Ah, I confirmed that the required option is missing from the command you gave. Also I confirmed that if required option `-tags=sqlite_vtable` is missing, then the build fails with the exact same error log.

```
$ go build -tags=sqlite_vtable gitqlite.go
```

**Comment by patrickdevivo** [comment]
Hi @erezsh please try running `make build` with your newly upgraded go version (I'm guessing the build failure you experienced on go1.10 was due to the project not being cloned into your GOPATH, but I could be wrong). go1.14 shouldn't have this requirement and `make build` will run exactly what @youngminz commented to produce a binary.

I'm sorry it wasn't super easy to setup! I know the installation docs could use some work. I've been thinking about how best to distribute this as well and hope to add a homebrew installation at least.

Thanks for taking the time and hopefully the experience can be improved!

**Comment by erezsh** [comment]
`make build` worked. Of course I still had to `chdmod +x` and copy it to the bin folder.

Any idea what I'm doing wrong in this query?

```shell
gitqlite "SELECT count(*) FROM commits WHERE [AUTHOR NAME] == 'foo' "
no such column: AUTHOR NAME
```

**Comment by patrickdevivo** [comment]
@erezsh try `gitqlite "SELECT count(*) FROM commits WHERE author_name == 'foo' "`

The README also enumerates the column names: https://github.com/augmentable-dev/gitqlite#commits FYI

**Comment by erezsh** [comment]
That's great, I just learned Wednesday is my most productive day, commit-wise :)

`SUM(additions)` is very slow for some reason, but other than that everything's working pretty well!

**Comment by patrickdevivo** [comment]
@erezsh haha nice! Yes, it's a known issue currently that pulling out commit stats (additions/deletions) is an expensive operation (unfortunately). I have a note to investigate, but a solution probably lies in a change the `go-git` dependency somewhere/somehow.

I'm going to close out this issue as I think your original ask was answered? The installation instructions do need some love, so that will be improved soon (note the TODO there)
